### ISSUE TITLE
Issue with Build

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.ide#3]
Hi,

I tried following the docs and deploy locally the eclipse che instance. I encountered the below issue while trying to compile eclipse che.

```ThinkPad-T530:~/kuksa-hackathon_01_19/kuksa.ide$ docker run -ti -v ~/.m2:/home/user/.m2 -v `pwd`:/che eclipse/che-dev:nightly sh -c "mvn clean install"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.116 s
[INFO] Finished at: 2019-01-17T11:27:30Z
[INFO] Final Memory: 7M/300M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/projects). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException ```

**Comment by lukaskrawczyk** [comment]
There was an error regarding a repository that has moved to mavencentral. While I was able to fix this, a new error regarding gwt appeared.

Maybe someone with better understanding of GWT could take a look into this:

<pre>[INFO] <b>--- </b><font color="#4E9A06">gwt-maven-plugin:1.0-rc-8:enforce-encoding</font> <b>(default-enforce-encoding)</b> @ <font color="#06989A">yocto-support-ide</font><b> ---</b>
[INFO] 
[INFO] <b>--- </b><font color="#4E9A06">gwt-maven-plugin:1.0-rc-8:add-super-sources</font> <b>(default-add-super-sources)</b> @ <font color="#06989A">yocto-support-ide</font><b> ---</b>
[INFO] 
[INFO] <b>--- </b><font color="#4E9A06">gwt-maven-plugin:1.0-rc-8:add-test-super-sources</font> <b>(default-add-test-super-sources)</b> @ <font color="#06989A">yocto-support-ide</font><b> ---</b>
[INFO] 
[INFO] <b>--- </b><font color="#4E9A06">gwt-maven-plugin:1.0-rc-8:generate-module</font> <b>(default-generate-module)</b> @ <font color="#06989A">yocto-support-ide</font><b> ---</b>
[INFO] <b>------------------------------------------------------------------------</b>
[INFO] <b>Reactor Summary:</b>
[INFO] 
[INFO] Kuksa IDE .......................................... <font color="#8AE234"><b>SUCCESS</b></font> [  1.079 s]
[INFO] Kuksa IDE :: Plugins ............................... <font color="#8AE234"><b>SUCCESS</b></font> [  0.021 s]
[INFO] Kuksa IDE :: Plugins :: Yocto Support .............. <font color="#8AE234"><b>SUCCESS</b></font> [  0.021 s]
[INFO] Kuksa IDE :: Plugins :: Yocto Support :: IDE ....... <font color="#EF2929"><b>FAILURE</b></font> [  3.408 s]
[INFO] Kuksa IDE :: Plugins :: Remote Target .............. <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Plugins :: Remote Target :: IDE ....... <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly .......................... <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly :: Workspace Agent Assembly <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly :: Workspace Agent Tomcat Assembly <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly :: IDE Assembly .......... <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Stacks ................................ <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly :: Workspace Master War .. <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Samples ............................... <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] Kuksa IDE :: Che Assembly :: Assemblies Tomcat ..... <font color="#FCE94F"><b>SKIPPED</b></font>
[INFO] <b>------------------------------------------------------------------------</b>
[INFO] <font color="#EF2929"><b>BUILD FAILURE</b></font>
[INFO] <b>------------------------------------------------------------------------</b>
[INFO] Total time: 5.453 s
[INFO] Finished at: 2019-01-25T06:23:13Z
[INFO] Final Memory: 54M/1362M
[INFO] <b>------------------------------------------------------------------------</b>
[ERROR] Failed to execute goal <font color="#4E9A06">net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:generate-module</font> <b>(default-generate-module)</b> on project <font color="#06989A">yocto-support-ide</font>: <font color="#EF2929"><b>/home/user/che-build/plugins/yocto-support/yocto-support-ide/target/classes/org/eclipse/che/kuksa/yocto/ide/YoctoSupportExtension.gwt.xml (No such file or directory)</b></font> -&gt; <b>[Help 1]</b>
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[ERROR] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   <b>mvn &lt;goals&gt; -rf :yocto-support-ide</b>
</pre>

**Comment by lukaskrawczyk** [comment]
Some more details on what I found so far:

There is a major difference between this extension and the [official examples](https://github.com/che-samples/che-ide-extension) regarding the extension class. While [`SampleMenuExtension`](https://github.com/che-samples/che-ide-extension/blob/a5d076fadda1239ba4fbe99965c6164b039d88c9/plugins/plugin-menu/plugin-menu-ide/src/main/java/org/eclipse/che/sample/ide/SampleMenuExtension.java#L24) injects dependencies into the method prepareActions(), the [resp. counterpart in this plugin](https://github.com/eclipse/kuksa.ide/blob/e6538e59e779f18b9ac7ae5d2a576d1e3ef83fc0/plugins/yocto-support/yocto-support-ide/src/main/java/org/eclipse/che/kuksa/yocto/ide/YoctoSupportExtension.java#L20) just provides an empty constructor. 

Since the new error addresses `YoctoSupportExtension.gwt.xml`, I can imagine GWT is not creating this file due to its different structure / missing injection. As the build has been working in the past, I'm wondering if something in the way how the build treats this file has changed in the meantime.

**Comment by daschubert** [comment]
Hi,

just a small remark. I guess the folder containing the pom.xml should be mounted to /projects.
```
docker run -ti -v ~/.m2:/home/user/.m2 -v `pwd`:/projects eclipse/che-dev:nightly sh -c "mvn clean install"
```

However, this still does not fix the build:

```
[INFO]
 Reactor Summary:
[INFO] 
[INFO] Kuksa IDE .......................................... SUCCESS [  3.306 s]\
[INFO] Kuksa IDE :: Plugins ............................... SUCCESS [  0.102 s]  
[INFO] Kuksa IDE :: Plugins :: Yocto Support .............. SUCCESS [  0.094 s]  
[INFO] Kuksa IDE :: Plugins :: Yocto Support :: IDE ....... SUCCESS [ 11.376 s]
[INFO] Kuksa IDE :: Plugins :: Remote Target .............. SUCCESS [  0.052 s]
[INFO] Kuksa IDE :: Plugins :: Remote Target :: IDE ....... SUCCESS [  1.656 s]
[INFO] Kuksa IDE :: Che Assembly .......................... SUCCESS [  0.047 s]
[INFO] Kuksa IDE :: Che Assembly :: Workspace Agent Assembly SUCCESS [  7.326 s]
[INFO] Kuksa IDE :: Che Assembly :: Workspace Agent Tomcat Assembly SUCCESS [  4.729 s]
[INFO] Kuksa IDE :: Che Assembly :: IDE Assembly .......... FAILURE [01:14 min]
[INFO] Kuksa IDE :: Stacks ................................ SKIPPED
[INFO] Kuksa IDE :: Che Assembly :: Workspace Master War .. SKIPPED
[INFO] Kuksa IDE :: Samples ............................... SKIPPED
[INFO] Kuksa IDE :: Che Assembly :: Assemblies Tomcat ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
I hope this helps.

**Comment by lukaskrawczyk** [comment]
Hi,

thanks for the remark.

Using your command I'm still receiving the same error as before. Have you pulled the [latest commit](https://github.com/eclipse/kuksa.ide/tree/e6538e59e779f18b9ac7ae5d2a576d1e3ef83fc0) of kuksa.ide (with versions bumbed to 6.17.0), or are you still using the [old one](https://github.com/eclipse/kuksa.ide/tree/7c808cf77fed4d183bc779efb217933c1a34f577) (6.7.0-SNAPSHOT)?

**Comment by daschubert** [comment]
I already had a call with Lukas. However, as this might be interesting for others: We are both working on the same revision with different results.

**Comment by lukaskrawczyk** [comment]
For the sake of completeness, here are the commands I'm using.
```
# Start in a clean directory
mkdir kuksa-test && cd kuksa-test
# Clone git repo
git clone https://github.com/eclipse/kuksa.ide.git
# Go to Kuksa.ide directory
cd kuksa.ide
# Run Build
docker run -ti -v /tmp:/home/user/.m2 -v `pwd`:/home/user/che-build -v `pwd`:/projects eclipse/che-dev:nightly sh -c "mvn clean install"
```

I switched the .m2 folder to eliminate the possibility of a cache related error

**Comment by lukaskrawczyk** [comment]
Thanks to @daschubert I was able to fix the compilation errors with the most recent commits (at least using his virtual machine)

@rai20 did this solve your problem?

**Comment by rohoet** [comment]
Build fixed.
The next step is to verify the AGL / Yocto stacks as mentioned in issue #2.
